# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PYGAlm3gV2x6I3CdzkxHutWR51C5bkSi
"""

import cobra
from cobra.io import load_model

model = load_model("e_coli_core")
ecolicore=cobra.flux_analysis.variability.find_blocked_reactions(model)
model = load_model("iAB_RBC_283")
iAB_RBC_283=cobra.flux_analysis.variability.find_blocked_reactions(model)
model = load_model("iNF517")
iNF517=cobra.flux_analysis.variability.find_blocked_reactions(model)
model = load_model("iNJ661")
iNJ661=cobra.flux_analysis.variability.find_blocked_reactions(model)

classic={}
f=open("cls")

for line in f:
  if line[0]==">":
    name=line[1:]
    classic[name+"_rev"]=[]
    classic[name+"_irrev"]=[]
    flag=False
  elif line[0]=="#":
    flag=not flag

  elif flag:
    classic[name+"_irrev"].append(line[:len(line)-1])
  else:
    classic[name+"_rev"].append(line[:len(line)-1])

print("e_coli_core")
print(len(e_coli_core),len(classic["e_coli_core.json\n_rev"]+classic["e_coli_core.json\n_irrev"]))

print("iAB_RBC_283")
print(len(iAB_RBC_283),len(classic["iAB_RBC_283.json\n_rev"]+classic["iAB_RBC_283.json\n_irrev"]))

print("iNF517")
print(len(iNF517),len(classic["iNF517.json\n_rev"]+classic["iNF517.json\n_irrev"]))

print("iNJ661")
print(len(iNJ661),len(classic["iNJ661.json\n_rev"]+classic["iNJ661.json\n_irrev"]))

modern={}
f=open("modern")

for line in f:
  if line[0]==">":
    name=line[1:]
    modern[name]=[]

  else:
    modern[name].append(line[:len(line)-1])

print("e_coli_core")
print(len(modern["e_coli_core.json\n"]),len(classic["e_coli_core.json\n_irrev"]))

print("iAB_RBC_283")
print(len(modern["iAB_RBC_283.json\n"]),len(classic["iAB_RBC_283.json\n_irrev"]))

print("iNF517")
print(len(modern["iNF517.json\n"]),len(classic["iNF517.json\n_irrev"]))

print("iNJ661")
print(len(modern["iNJ661.json\n"]),len(classic["iNJ661.json\n_irrev"]))